import Mathlib.Algebra.Quaternion
import Mathlib.Data.Real.Basic
import Mathlib.GroupTheory.Complement
import Mathlib.GroupTheory.SemidirectProduct

/-!
# Subgroup-first binary tetrahedral spike

This file checks whether the binary tetrahedral group can first be constructed
inside the unit quaternions and only then identified with a semidirect product.
It is a feasibility spike, not a library module.

The intended benefit is precise: once the quaternion subgroup is the ambient
group of the construction, faithfulness should follow from subtype inclusion
instead of a separate calculation on a `Q₈ ⋊ C₃` normal form.
-/

open scoped Quaternion

namespace Fgap.Spike.Subgroup

noncomputable section

abbrev UnitQuaternions := (ℍ[ℝ])ˣ

/-- The eight quaternion units inside `ℍ[ℝ]ˣ`.

Constructing the units `±1`, `±i`, `±j`, and `±k`, proving closure, and giving
the resulting subgroup a usable finite normal form are concrete obligations
not supplied by the current quaternion API. -/
def quaternionUnits : Subgroup UnitQuaternions := by
  sorry

/-- An order-three Hurwitz unit that cyclically conjugates `i`, `j`, and `k`.

The expected value is one of `(1 ± i ± j ± k) / 2`, with signs fixed to match
the chosen cycling convention. Its unit proof and coordinate calculations are
part of the spike boundary. -/
def hurwitzCycle : UnitQuaternions := by
  sorry

/-- The cyclic subgroup generated by the Hurwitz unit. -/
def cycleUnits : Subgroup UnitQuaternions :=
  Subgroup.zpowers hurwitzCycle

/-- The subgroup generated by the quaternion and order-three sectors. -/
def binaryTetrahedralUnits : Subgroup UnitQuaternions :=
  quaternionUnits ⊔ cycleUnits

private abbrev Q :=
  quaternionUnits.subgroupOf binaryTetrahedralUnits

private abbrev C :=
  cycleUnits.subgroupOf binaryTetrahedralUnits

/-- Conjugation by the Hurwitz unit normalizes the quaternion subgroup.

At generator level this is the calculation that cyclically permutes `i`, `j`,
and `k`. It is the main concrete bridge between quaternion arithmetic and the
subgroup structure. -/
theorem quaternionUnits_normal_in_binaryTetrahedral :
    Q.Normal := by
  sorry

attribute [local instance] quaternionUnits_normal_in_binaryTetrahedral

/-- The quaternion and order-three subgroups are complementary.

A finite proof can use their orders `8` and `3`, trivial intersection, and the
fact that they generate the 24-element ambient subgroup. These cardinality and
normal-form calculations remain explicit mathematical obligations. -/
theorem quaternion_cycle_complement :
    Q.IsComplement' C := by
  sorry

/-- The subgroup-first semidirect-product presentation.

This definition is provided directly by current mathlib once normality and
complementarity have been proved. -/
noncomputable def semidirectEquiv :
    Q ⋊[(Q.normalizerMonoidHom).comp
      (Subgroup.inclusion (Q.normalizer_eq_top ▸ le_top))] C
      ≃* binaryTetrahedralUnits :=
  SemidirectProduct.mulEquivSubgroup quaternion_cycle_complement

/-- Inclusion of the subgroup-first model into the unit quaternions. -/
noncomputable def toQuaternionUnits :
    Q ⋊[(Q.normalizerMonoidHom).comp
      (Subgroup.inclusion (Q.normalizer_eq_top ▸ le_top))] C
      →* UnitQuaternions :=
  binaryTetrahedralUnits.subtype.comp semidirectEquiv.toMonoidHom

/-- Faithfulness is inherited from the equivalence and subtype inclusion. -/
theorem toQuaternionUnits_injective :
    Function.Injective toQuaternionUnits :=
  binaryTetrahedralUnits.subtype_injective.comp semidirectEquiv.injective

end

end Fgap.Spike.Subgroup
