import Mathlib.Algebra.Quaternion
import Mathlib.Data.Real.Basic
import Mathlib.GroupTheory.Complement
import Mathlib.GroupTheory.SemidirectProduct
import Mathlib.Tactic.NormNum

/-!
# Subgroup-first binary tetrahedral spike

This file checks whether the binary tetrahedral group can first be constructed
inside the unit quaternions and only then identified with a semidirect product.
It is a feasibility spike, not a library module.

The intended benefit is precise: once the quaternion subgroup is the ambient
group of the construction, faithfulness should follow from subtype inclusion
instead of a separate calculation on a `Q₈ ⋊ C₃` normal form.
-/

open scoped Quaternion

namespace Fgap.Spike.Subgroup

noncomputable section

abbrev UnitQuaternions := (ℍ[ℝ])ˣ

/-- The quaternion `i`, packaged as a unit. -/
def quaternionI : UnitQuaternions :=
  Units.mk0 (⟨0, 1, 0, 0⟩ : ℍ[ℝ]) (by
    intro h
    have him := congrArg (fun q : ℍ[ℝ] => q.imI) h
    norm_num at him)

/-- The quaternion `j`, packaged as a unit. -/
def quaternionJ : UnitQuaternions :=
  Units.mk0 (⟨0, 0, 1, 0⟩ : ℍ[ℝ]) (by
    intro h
    have hjm := congrArg (fun q : ℍ[ℝ] => q.imJ) h
    norm_num at hjm)

/-- The subgroup of unit quaternions generated by `i` and `j`.

Showing that its carrier is exactly `±1`, `±i`, `±j`, and `±k`, and giving it
a usable finite normal form are concrete obligations not supplied by the
current quaternion API. -/
def quaternionUnits : Subgroup UnitQuaternions :=
  Subgroup.closure {quaternionI, quaternionJ}

/-- The quaternion underlying the order-three Hurwitz unit. -/
def hurwitzCycleValue : ℍ[ℝ] :=
  ⟨-(1 / 2), 1 / 2, 1 / 2, 1 / 2⟩

/-- An order-three Hurwitz unit that cyclically conjugates `i`, `j`, and `k`.

The chosen value is `(-1 + i + j + k) / 2`. Its nonzero proof is immediate
from the real coordinate; the conjugation calculations remain part of the
spike boundary. -/
def hurwitzCycle : UnitQuaternions :=
  Units.mk0 hurwitzCycleValue (by
    intro h
    have hre := congrArg (fun q : ℍ[ℝ] => q.re) h
    norm_num [hurwitzCycleValue] at hre)

/-- The chosen Hurwitz unit has order dividing three. -/
theorem hurwitzCycle_pow_three : hurwitzCycle ^ 3 = 1 := by
  apply Units.ext
  ext <;> norm_num [hurwitzCycle, hurwitzCycleValue, pow_succ,
    Quaternion.re_mul, Quaternion.imI_mul, Quaternion.imJ_mul, Quaternion.imK_mul]

/-- The cyclic subgroup generated by the Hurwitz unit. -/
def cycleUnits : Subgroup UnitQuaternions :=
  Subgroup.zpowers hurwitzCycle

/-- The subgroup generated by the quaternion and order-three sectors. -/
def binaryTetrahedralUnits : Subgroup UnitQuaternions :=
  quaternionUnits ⊔ cycleUnits

private abbrev Q :=
  quaternionUnits.subgroupOf binaryTetrahedralUnits

private abbrev C :=
  cycleUnits.subgroupOf binaryTetrahedralUnits

/-- Conjugation by the Hurwitz unit normalizes the quaternion subgroup.

At generator level this is the calculation that cyclically permutes `i`, `j`,
and `k`. It is the main concrete bridge between quaternion arithmetic and the
subgroup structure. -/
theorem quaternionUnits_normal_in_binaryTetrahedral :
    Q.Normal := by
  sorry

attribute [local instance] quaternionUnits_normal_in_binaryTetrahedral

/-- The quaternion and order-three subgroups are complementary.

A finite proof can use their orders `8` and `3`, trivial intersection, and the
fact that they generate the 24-element ambient subgroup. These cardinality and
normal-form calculations remain explicit mathematical obligations. -/
theorem quaternion_cycle_complement :
    Q.IsComplement' C := by
  sorry

/-- The subgroup-first semidirect-product presentation.

This definition is provided directly by current mathlib once normality and
complementarity have been proved. -/
noncomputable def semidirectEquiv :
    Q ⋊[(Q.normalizerMonoidHom).comp
      (Subgroup.inclusion (Q.normalizer_eq_top ▸ le_top))] C
      ≃* binaryTetrahedralUnits :=
  SemidirectProduct.mulEquivSubgroup quaternion_cycle_complement

/-- Inclusion of the subgroup-first model into the unit quaternions. -/
noncomputable def toQuaternionUnits :
    Q ⋊[(Q.normalizerMonoidHom).comp
      (Subgroup.inclusion (Q.normalizer_eq_top ▸ le_top))] C
      →* UnitQuaternions :=
  binaryTetrahedralUnits.subtype.comp semidirectEquiv.toMonoidHom

/-- Faithfulness is inherited from the equivalence and subtype inclusion. -/
theorem toQuaternionUnits_injective :
    Function.Injective toQuaternionUnits :=
  binaryTetrahedralUnits.subtype_injective.comp semidirectEquiv.injective

end

end Fgap.Spike.Subgroup
