name = "FGAP"
defaultTargets = ["FGAP"]
platformIndependent = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "e0824fdc1cf95ea19518210636c74510a36acb05"

[[lean_lib]]
name = "FGAP"
globs = ["FGAP.*"]
leanOptions = { weak.linter.mathlibStandardSet = true, weak.linter.style.longFile = 1500, weak.linter.style.longFileDefValue = 1500, weak.linter.style.header = false, warningAsError = true }
