import Mathlib.Algebra.Quaternion
import Mathlib.Data.ZMod.QuotientGroup
import Mathlib.Data.Real.Basic
import Mathlib.GroupTheory.SemidirectProduct
import Mathlib.GroupTheory.SpecificGroups.Cyclic
import Mathlib.GroupTheory.SpecificGroups.Quaternion

/-!
# Abstract-first binary tetrahedral spike

This file checks the interfaces needed to construct the binary tetrahedral group
as `Q₈ ⋊ C₃` before relating it to unit quaternions. It is a feasibility spike,
not a library module.

The construction below is concrete except for two named obligations: the
order-three automorphism of `Q₈`, and the compatibility of the eventual
quaternion map with the resulting action.
-/

open scoped Quaternion

namespace Fgap.Spike.Abstract

abbrev Q8 := QuaternionGroup 2

abbrev C3 := Multiplicative (ZMod 3)

/-- The automorphism that cyclically permutes the three quaternion generators.

The current `QuaternionGroup` API gives a useful normal form, but does not
provide this automorphism. Defining it and proving that it respects
multiplication is the first concrete obligation exposed by this spike. -/
def cycle : MulAut Q8 := by
  sorry

/-- The cycling automorphism has order three.

This should follow from its action on the quaternion generators. Keeping it
separate from the automorphism construction makes the cyclic-action interface
below independent of the chosen normal-form proof. -/
theorem orderOf_cycle : orderOf cycle = 3 := by
  sorry

private abbrev Cycle := Subgroup.zpowers cycle

private theorem cycle_generates (x : Cycle) :
    x ∈ Subgroup.zpowers (⟨cycle, Subgroup.mem_zpowers cycle⟩ : Cycle) := by
  rcases x.property with ⟨n, hn⟩
  refine ⟨n, ?_⟩
  apply Subtype.ext
  exact hn

private theorem card_cycle : Nat.card Cycle = 3 := by
  rw [Nat.card_zpowers, orderOf_cycle]

/-- The canonical copy of `C₃` generated by `cycle`. -/
noncomputable def cycleEquiv : C3 ≃* Cycle :=
  zmodMulEquivOfGenerator cycle_generates card_cycle

/-- The action of `C₃` on `Q₈` induced by the cycling automorphism. -/
noncomputable def action : C3 →* MulAut Q8 :=
  (Subgroup.subtype Cycle).comp cycleEquiv.toMonoidHom

/-- The abstract semidirect-product model of the binary tetrahedral group. -/
abbrev BinaryTetrahedral := Q8 ⋊[action] C3

/-- A proposed map from the abstract model to unit quaternions.

The factor maps can be written once concrete quaternion units are chosen.
Their compatibility with `action` is the second substantial obligation: it is
the statement that conjugation by the Hurwitz unit realizes `cycle`. -/
def toQuaternionUnits : BinaryTetrahedral →* (ℍ[ℝ])ˣ := by
  sorry

/-- Faithfulness of the abstract realization.

A direct proof needs a normal form for the semidirect product and separation of
the three cosets in the quaternion image. The subgroup-first spike tests
whether this can instead be inherited from subtype inclusion. -/
theorem toQuaternionUnits_injective :
    Function.Injective toQuaternionUnits := by
  sorry

end Fgap.Spike.Abstract
