/-
Copyright (c) 2026 utensil. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import FGAP.GroupTheory.BinaryTetrahedral.Cyclic
public import FGAP.GroupTheory.BinaryTetrahedral.QuaternionGroup
public import Mathlib.GroupTheory.SemidirectProduct

import Mathlib.Algebra.Group.Subgroup.Pointwise
import Mathlib.Tactic.NormNum

/-!
# The binary tetrahedral subgroup

This file combines the concrete quaternion subgroup and the order-three
Hurwitz subgroup inside the invertible real quaternions. The Hurwitz
conjugation cycle proves normalization, while the coprime factor orders prove
that the factors intersect trivially.

The concrete subgroup, its internal factors, and the associated external
semidirect product are kept as distinct models.

## Main declarations

* `BinaryTetrahedral.hurwitzCyclic_le_normalizer_quaternionSubgroup`: the
  Hurwitz subgroup normalizes the quaternion subgroup.
* `BinaryTetrahedral.quaternionSubgroup_inf_hurwitzCyclic`: the two concrete
  factors intersect trivially.
* `BinaryTetrahedral.binaryTetrahedral`: the concrete subgroup generated by
  the quaternion and Hurwitz subgroups.
* `BinaryTetrahedral.binaryTetrahedral_isComplement`: the internal factors
  are complementary.
* `BinaryTetrahedral.binaryTetrahedralEquiv`: the external semidirect product
  is equivalent to the concrete subgroup.

## References

* John Voight, *Quaternion Algebras*, §11.2.4, p. 168.
  <https://doi.org/10.1007/978-3-030-56694-4>
* Forest notes `fgap-000E` through `fgap-000L`.
-/

public section

open scoped Pointwise

namespace BinaryTetrahedral

noncomputable section

private theorem quaternionK_mem_quaternionSubgroup :
    quaternionK ∈ quaternionSubgroup := by
  rw [quaternionSubgroup_eq_closure]
  have hi : quaternionI ∈ Subgroup.closure {quaternionI, quaternionJ} :=
    Subgroup.subset_closure (by simp)
  have hj : quaternionJ ∈ Subgroup.closure {quaternionI, quaternionJ} :=
    Subgroup.subset_closure (by simp)
  have hij := (Subgroup.closure {quaternionI, quaternionJ}).mul_mem hi hj
  convert hij using 1
  ext <;> rw [coe_quaternionK] <;>
    norm_num [quaternionI, quaternionJ, Quaternion.re_mul,
      Quaternion.imI_mul, Quaternion.imJ_mul, Quaternion.imK_mul]

private theorem hurwitzCycle_mem_normalizer_quaternionSubgroup :
    hurwitzCycle ∈ Subgroup.normalizer quaternionSubgroup := by
  rw [Subgroup.mem_normalizer_iff_map_conj_eq]
  apply Subgroup.eq_of_le_of_card_ge
  · rintro _ ⟨q, hq, rfl⟩
    change hurwitzCycle * q * hurwitzCycle⁻¹ ∈ quaternionSubgroup
    rw [quaternionSubgroup_eq_closure] at hq ⊢
    induction hq using Subgroup.closure_induction with
    | mem q hq =>
        rcases hq with rfl | rfl
        · rw [hurwitzCycle_conj_quaternionI,
            ← quaternionSubgroup_eq_closure]
          exact quaternionK_mem_quaternionSubgroup
        · simpa [hurwitzCycle_conj_quaternionJ] using
            (Subgroup.subset_closure
              (Set.mem_insert quaternionI {quaternionJ}))
    | one => simp
    | mul x y _ _ hx hy =>
        simpa [mul_assoc] using
          (Subgroup.closure {quaternionI, quaternionJ}).mul_mem hx hy
    | inv x _ hx =>
        simpa [mul_assoc] using
          (Subgroup.closure {quaternionI, quaternionJ}).inv_mem hx
  · rw [Subgroup.card_map_of_injective (MulAut.conj hurwitzCycle).injective]

/-- The order-three Hurwitz subgroup normalizes the concrete quaternion
subgroup. -/
theorem hurwitzCyclic_le_normalizer_quaternionSubgroup :
    hurwitzCyclic ≤ Subgroup.normalizer quaternionSubgroup := by
  rw [hurwitzCyclic_eq_zpowers]
  rw [Subgroup.zpowers_le]
  exact hurwitzCycle_mem_normalizer_quaternionSubgroup

/-- The concrete quaternion subgroup and the order-three Hurwitz subgroup
intersect only in the identity. -/
theorem quaternionSubgroup_inf_hurwitzCyclic :
    quaternionSubgroup ⊓ hurwitzCyclic = ⊥ := by
  apply Disjoint.eq_bot
  apply Subgroup.disjoint_of_coprime_natCard
  rw [hurwitzCyclic_card, Nat.card_eq_fintype_card,
    card_quaternionSubgroup]
  decide

/-- The concrete binary tetrahedral subgroup generated by the quaternion
subgroup and the order-three Hurwitz subgroup. -/
def binaryTetrahedral : Subgroup InvertibleQuaternions :=
  quaternionSubgroup ⊔ hurwitzCyclic

/-- The concrete binary tetrahedral subgroup is the normalized set product
of its quaternion and Hurwitz factors. -/
theorem binaryTetrahedral_carrier :
    (binaryTetrahedral : Set InvertibleQuaternions) =
      ((quaternionSubgroup : Set InvertibleQuaternions) *
        (hurwitzCyclic : Set InvertibleQuaternions) :
          Set InvertibleQuaternions) := by
  exact Subgroup.coe_mul_of_right_le_normalizer_left _ _
    hurwitzCyclic_le_normalizer_quaternionSubgroup

/-- The internal quaternion factor of the concrete binary tetrahedral
subgroup. -/
@[expose]
def binaryTetrahedralQuaternion : Subgroup binaryTetrahedral :=
  quaternionSubgroup.subgroupOf binaryTetrahedral

/-- The internal order-three factor of the concrete binary tetrahedral
subgroup. -/
@[expose]
def binaryTetrahedralCyclic : Subgroup binaryTetrahedral :=
  hurwitzCyclic.subgroupOf binaryTetrahedral

/-- The internal quaternion factor is normal in the concrete binary
tetrahedral subgroup. -/
noncomputable instance : binaryTetrahedralQuaternion.Normal := by
  change (quaternionSubgroup.subgroupOf
    (quaternionSubgroup ⊔ hurwitzCyclic)).Normal
  rw [Subgroup.normal_subgroupOf_iff_le_normalizer le_sup_left]
  exact sup_le Subgroup.le_normalizer
    hurwitzCyclic_le_normalizer_quaternionSubgroup

/-- The internal quaternion and Hurwitz factors have trivial intersection. -/
theorem binaryTetrahedral_factors_disjoint :
    Disjoint binaryTetrahedralQuaternion binaryTetrahedralCyclic := by
  rw [disjoint_iff]
  change (quaternionSubgroup ⊓ hurwitzCyclic).subgroupOf
    binaryTetrahedral = ⊥
  rw [quaternionSubgroup_inf_hurwitzCyclic, Subgroup.bot_subgroupOf]

/-- The internal quaternion and Hurwitz factors are complementary: every
element has a unique factorization with the quaternion factor on the left. -/
theorem binaryTetrahedral_isComplement :
    binaryTetrahedralQuaternion.IsComplement' binaryTetrahedralCyclic := by
  apply Subgroup.isComplement'_of_disjoint_and_mul_eq_univ
    binaryTetrahedral_factors_disjoint
  rw [← Subgroup.normal_mul]
  exact congrArg (fun H : Subgroup binaryTetrahedral =>
    (H : Set binaryTetrahedral)) (codisjoint_iff.mp
      (Subgroup.codisjoint_subgroupOf_sup
        quaternionSubgroup hurwitzCyclic))

private theorem natCard_subgroupOf {G : Type*} [Group G]
    {H K : Subgroup G} (h : H ≤ K) :
    Nat.card (H.subgroupOf K) = Nat.card H :=
  Nat.card_congr (Subgroup.subgroupOfEquivOfLe h).toEquiv

/-- The concrete binary tetrahedral subgroup has twenty-four elements. -/
theorem binaryTetrahedral_card :
    Nat.card binaryTetrahedral = 24 := by
  have h := binaryTetrahedral_isComplement.card_mul
  change Nat.card (quaternionSubgroup.subgroupOf binaryTetrahedral) *
    Nat.card (hurwitzCyclic.subgroupOf binaryTetrahedral) =
      Nat.card binaryTetrahedral at h
  rw [natCard_subgroupOf (show quaternionSubgroup ≤ binaryTetrahedral from
      le_sup_left),
    Nat.card_eq_fintype_card, card_quaternionSubgroup,
    natCard_subgroupOf (show hurwitzCyclic ≤ binaryTetrahedral from
      le_sup_right),
    hurwitzCyclic_card] at h
  norm_num at h ⊢
  exact h.symm

/-- Conjugation by the internal Hurwitz factor on the internal quaternion
factor. -/
abbrev binaryTetrahedralAction :
    binaryTetrahedralCyclic →* MulAut binaryTetrahedralQuaternion :=
  (binaryTetrahedralQuaternion.normalizerMonoidHom).comp
    (Subgroup.inclusion
      (binaryTetrahedralQuaternion.normalizer_eq_top ▸ le_top))

/-- The external semidirect product determined by Hurwitz conjugation is
equivalent to the concrete binary tetrahedral subgroup. The source consists
of pairs of internal-factor elements; the target consists of invertible real
quaternions. -/
@[expose]
noncomputable def binaryTetrahedralEquiv :
    binaryTetrahedralQuaternion ⋊[binaryTetrahedralAction]
      binaryTetrahedralCyclic ≃* binaryTetrahedral :=
  SemidirectProduct.mulEquivSubgroup binaryTetrahedral_isComplement

@[simp]
theorem binaryTetrahedralEquiv_apply
    (x : binaryTetrahedralQuaternion ⋊[binaryTetrahedralAction]
      binaryTetrahedralCyclic) :
    binaryTetrahedralEquiv x =
      (x.left : binaryTetrahedral) * (x.right : binaryTetrahedral) :=
  rfl

end

end BinaryTetrahedral
