/-
Copyright (c) 2026 utensil. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import FGAP.GroupTheory.BinaryTetrahedral.Quaternion
public import Mathlib.GroupTheory.SpecificGroups.Cyclic

import Mathlib.Tactic.NormNum

/-!
# The order-three Hurwitz subgroup

The selected Hurwitz unit generates a concrete three-element subgroup of the
invertible real quaternions. This file identifies its exact order and gives
the subgroup an explicit cyclic-group interface.

## Main declarations

* `BinaryTetrahedral.hurwitzCycle_order`: the selected Hurwitz unit has exact
  order three.
* `BinaryTetrahedral.hurwitzCyclic`: the subgroup generated by the Hurwitz
  unit.
* `BinaryTetrahedral.hurwitzCyclic_carrier` and
  `BinaryTetrahedral.hurwitzCyclic_card`: its concrete normal form and
  cardinality.
* `BinaryTetrahedral.hurwitzCyclicEquiv`: the explicit multiplicative
  equivalence from `Multiplicative (ZMod 3)`.

## References

* John Voight, *Quaternion Algebras*, §11.2.4, p. 168.
  <https://doi.org/10.1007/978-3-030-56694-4>
* Forest note `fgap-000B`, “the cyclic subgroup generated by the Hurwitz
  unit.”
-/

public section

open scoped Quaternion

namespace BinaryTetrahedral

noncomputable section

/-- The selected Hurwitz unit has exact multiplicative order three. -/
theorem hurwitzCycle_order : orderOf hurwitzCycle = 3 :=
  orderOf_eq_prime hurwitzCycle_pow_three hurwitzCycle_ne_one

/-- The subgroup generated by the selected Hurwitz unit. -/
def hurwitzCyclic : Subgroup InvertibleQuaternions :=
  Subgroup.zpowers hurwitzCycle

/-- The concrete normal form of the subgroup generated by the selected
Hurwitz unit. -/
theorem hurwitzCyclic_carrier :
    (hurwitzCyclic : Set InvertibleQuaternions) =
      {1, hurwitzCycle, hurwitzCycle ^ 2} := by
  classical
  ext x
  change x ∈ Subgroup.zpowers hurwitzCycle ↔ _
  rw [(isOfFinOrder_iff_pow_eq_one.2
    ⟨3, by norm_num, hurwitzCycle_pow_three⟩).mem_zpowers_iff_mem_range_orderOf,
    hurwitzCycle_order]
  simp only [Finset.mem_image, Finset.mem_range]
  constructor
  · rintro ⟨n, hn, rfl⟩
    interval_cases n <;> simp
  · rintro (rfl | rfl | rfl)
    · exact ⟨0, by norm_num, by simp⟩
    · exact ⟨1, by norm_num, by simp⟩
    · exact ⟨2, by norm_num⟩

/-- The subgroup generated by the selected Hurwitz unit has three elements. -/
theorem hurwitzCyclic_card :
    Nat.card hurwitzCyclic = 3 := by
  change Nat.card (Subgroup.zpowers hurwitzCycle) = 3
  rw [Nat.card_zpowers, hurwitzCycle_order]

noncomputable instance : Finite hurwitzCyclic :=
  Nat.finite_of_card_ne_zero (by simp [hurwitzCyclic_card])

private theorem mem_zpowers_hurwitzCyclic_generator (x : hurwitzCyclic) :
    x ∈ Subgroup.zpowers
      (⟨hurwitzCycle, Subgroup.mem_zpowers hurwitzCycle⟩ : hurwitzCyclic) := by
  obtain ⟨x, n, rfl⟩ := x
  exact ⟨n, rfl⟩

/-- The standard cyclic group of order three is multiplicatively equivalent
to the subgroup generated by the selected Hurwitz unit. -/
noncomputable def hurwitzCyclicEquiv :
    Multiplicative (ZMod 3) ≃* hurwitzCyclic :=
  zmodMulEquivOfGenerator mem_zpowers_hurwitzCyclic_generator hurwitzCyclic_card

@[simp]
theorem hurwitzCyclicEquiv_generator :
    hurwitzCyclicEquiv (Multiplicative.ofAdd 1) =
      ⟨hurwitzCycle, by
        simp [hurwitzCyclic]⟩ := by
  exact zmodMulEquivOfGenerator_apply_ofAdd_one
    mem_zpowers_hurwitzCyclic_generator hurwitzCyclic_card

end

end BinaryTetrahedral
