/-
Copyright (c) 2026 utensil. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import FGAP.GroupTheory.BinaryTetrahedral.Quaternion
public import Mathlib.Algebra.Group.Equiv.TypeTags
public import Mathlib.Data.ZMod.QuotientGroup

import Mathlib.Algebra.Group.TypeTags.Finite
import Mathlib.SetTheory.Cardinal.Finite
import Mathlib.Tactic.NormNum

/-!
# The order-three Hurwitz subgroup

The selected Hurwitz unit generates a concrete three-element subgroup of the
invertible real quaternions. This file identifies its exact order and gives
the subgroup an explicit cyclic-group interface.

## Main declarations

* `BinaryTetrahedral.hurwitzCycle_order`: the selected Hurwitz unit has exact
  order three.
* `BinaryTetrahedral.hurwitzCyclic`: the subgroup generated by the Hurwitz
  unit.
* `BinaryTetrahedral.hurwitzCyclic_carrier` and
  `BinaryTetrahedral.hurwitzCyclic_card`: its concrete normal form and
  cardinality.
* `BinaryTetrahedral.hurwitzCyclicEquiv`: the explicit multiplicative
  equivalence from `Multiplicative (ZMod 3)`.

## References

* John Voight, *Quaternion Algebras*, §11.2.4, p. 168.
  <https://doi.org/10.1007/978-3-030-56694-4>
* Forest note `fgap-000B`, “the cyclic subgroup generated by the Hurwitz
  unit.”
-/

public section

open scoped Quaternion

namespace BinaryTetrahedral

noncomputable section

/-- The selected Hurwitz unit has exact multiplicative order three. -/
theorem hurwitzCycle_order : orderOf hurwitzCycle = 3 :=
  orderOf_eq_prime hurwitzCycle_pow_three hurwitzCycle_ne_one

/-- The subgroup generated by the selected Hurwitz unit. -/
def hurwitzCyclic : Subgroup InvertibleQuaternions :=
  Subgroup.zpowers hurwitzCycle

/-- The concrete normal form of the subgroup generated by the selected
Hurwitz unit. -/
theorem hurwitzCyclic_carrier :
    (hurwitzCyclic : Set InvertibleQuaternions) =
      {1, hurwitzCycle, hurwitzCycle ^ 2} := by
  ext x
  constructor
  · intro hx
    obtain ⟨n, rfl⟩ := Subgroup.mem_zpowers_iff.mp hx
    have hcases :
        n % (orderOf hurwitzCycle : ℤ) = 0 ∨
          n % (orderOf hurwitzCycle : ℤ) = 1 ∨
          n % (orderOf hurwitzCycle : ℤ) = 2 := by
      rw [hurwitzCycle_order]
      omega
    rcases hcases with h | h | h
    · left
      rw [← zpow_mod_orderOf, h]
      simp
    · right
      left
      rw [← zpow_mod_orderOf, h]
      simp
    · right
      right
      rw [← zpow_mod_orderOf, h]
      rfl
  · rintro (rfl | rfl | rfl)
    · exact Subgroup.one_mem hurwitzCyclic
    · exact Subgroup.mem_zpowers hurwitzCycle
    · exact Subgroup.npow_mem_zpowers hurwitzCycle 2

private def integerPowers : ℤ →+ Additive hurwitzCyclic where
  toFun n :=
    Additive.ofMul
      ⟨hurwitzCycle ^ n, Subgroup.zpow_mem_zpowers hurwitzCycle n⟩
  map_zero' := by
    apply Additive.ext
    apply Subtype.ext
    simp
  map_add' m n := by
    apply Additive.ext
    apply Subtype.ext
    exact zpow_add hurwitzCycle m n

private theorem integerPowers_three : integerPowers 3 = 0 := by
  apply Additive.ext
  apply Subtype.ext
  exact hurwitzCycle_pow_three

/-- Raising the Hurwitz unit to an exponent modulo three, as a homomorphism
from the standard cyclic group. -/
def hurwitzCyclicHom : Multiplicative (ZMod 3) →* hurwitzCyclic :=
  AddMonoidHom.toMultiplicativeLeft
    (ZMod.lift 3 ⟨integerPowers, integerPowers_three⟩)

@[simp]
theorem hurwitzCyclicHom_generator :
    hurwitzCyclicHom (Multiplicative.ofAdd 1) =
      ⟨hurwitzCycle, by
        simp [hurwitzCyclic]⟩ := by
  apply Subtype.ext
  change Additive.toMul
      ((ZMod.lift 3 ⟨integerPowers, integerPowers_three⟩) 1) =
    hurwitzCycle
  rw [show (1 : ZMod 3) = ((1 : ℤ) : ZMod 3) by norm_num,
    ZMod.lift_coe]
  simp [integerPowers]

private theorem hurwitzCyclicHom_surjective :
    Function.Surjective hurwitzCyclicHom := by
  rintro ⟨x, hx⟩
  obtain ⟨n, rfl⟩ := Subgroup.mem_zpowers_iff.mp hx
  refine ⟨Multiplicative.ofAdd (n : ZMod 3), ?_⟩
  apply Subtype.ext
  simp [hurwitzCyclicHom, integerPowers]

/-- The subgroup generated by the selected Hurwitz unit has three elements. -/
theorem hurwitzCyclic_card :
    Nat.card hurwitzCyclic = 3 := by
  change Nat.card (Subgroup.zpowers hurwitzCycle) = 3
  rw [Nat.card_zpowers, hurwitzCycle_order]

noncomputable instance : Finite hurwitzCyclic :=
  show Finite (Subgroup.zpowers hurwitzCycle) from
    (isOfFinOrder_iff_pow_eq_one.2
      ⟨3, by norm_num, hurwitzCycle_pow_three⟩).finite_zpowers

/-- The standard cyclic group of order three is multiplicatively equivalent
to the subgroup generated by the selected Hurwitz unit. -/
noncomputable def hurwitzCyclicEquiv :
    Multiplicative (ZMod 3) ≃* hurwitzCyclic := by
  exact MulEquiv.ofBijective hurwitzCyclicHom <|
    (Nat.bijective_iff_surjective_and_card _).2
      ⟨hurwitzCyclicHom_surjective, by
        simp [hurwitzCyclic_card]⟩

@[simp]
theorem hurwitzCyclicEquiv_generator :
    hurwitzCyclicEquiv (Multiplicative.ofAdd 1) =
      ⟨hurwitzCycle, by
        simp [hurwitzCyclic]⟩ := by
  simp [hurwitzCyclicEquiv]

end

end BinaryTetrahedral
