/-
Copyright (c) 2026 utensil. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import FGAP.GroupTheory.BinaryTetrahedral.Quaternion
public import Mathlib.GroupTheory.SpecificGroups.Quaternion

import Mathlib.Tactic.FinCases
import Mathlib.Tactic.NormNum

/-!
# The quaternion subgroup

This file constructs the subgroup of invertible Hamiltonian quaternions
generated by `i` and `j`, then identifies it with mathlib's abstract
`QuaternionGroup 2`.

## Main declarations

* `BinaryTetrahedral.quaternionSubgroup`: the concrete quaternion subgroup.
* `BinaryTetrahedral.quaternionGroupEquiv`: the explicit equivalence
  `QuaternionGroup 2 ≃* quaternionSubgroup`.
* `BinaryTetrahedral.card_quaternionSubgroup`: the subgroup has 8
  elements.

## References

* John Voight, *Quaternion Algebras*, §11.2, p. 166.
  <https://doi.org/10.1007/978-3-030-56694-4>
* Forest notes `fgap-0009` and `fgap-000A`.
  <https://github.com/utensil/forest/tree/fgap>
-/

public section

open scoped Quaternion

namespace BinaryTetrahedral

noncomputable section

private theorem quaternionI_pow_four : quaternionI ^ 4 = 1 := by
  ext <;>
    norm_num [pow_succ, Quaternion.re_mul, Quaternion.imI_mul,
      Quaternion.imJ_mul, Quaternion.imK_mul]

/-- The homomorphism from the additive cyclic group `ZMod 4` to powers of `i`. -/
private noncomputable def quaternionIPowersAdd :
    ZMod 4 →+ Additive InvertibleQuaternions :=
  ZMod.lift 4
    ⟨zmultiplesHom (Additive InvertibleQuaternions) (Additive.ofMul quaternionI), by
      rw [zmultiplesHom_apply]
      change Additive.ofMul (quaternionI ^ (4 : ℤ)) = 0
      rw [zpow_ofNat, quaternionI_pow_four]
      rfl⟩

/-- Powers of `i`, indexed by the cyclic group `ZMod 4`. -/
private noncomputable def quaternionIPowers :
    Multiplicative (ZMod 4) →* InvertibleQuaternions :=
  quaternionIPowersAdd.toMultiplicativeLeft

@[simp]
private theorem quaternionIPowers_intCast (m : ℤ) :
    quaternionIPowers (Multiplicative.ofAdd (m : ZMod 4)) = quaternionI ^ m := by
  simp [quaternionIPowers, quaternionIPowersAdd, ZMod.lift_coe, zmultiplesHom_apply]

private theorem quaternionIPowers_val (r : ZMod 4) :
    quaternionIPowers (Multiplicative.ofAdd r) = quaternionI ^ r.val := by
  conv_lhs => rw [← ZMod.natCast_zmod_val r]
  calc
    quaternionIPowers (Multiplicative.ofAdd (r.val : ZMod 4)) =
        quaternionI ^ (r.val : ℤ) := quaternionIPowers_intCast (r.val : ℤ)
    _ = quaternionI ^ r.val := zpow_ofNat quaternionI r.val

@[simp]
private theorem quaternionIPowers_one :
    quaternionIPowers (Multiplicative.ofAdd (1 : ZMod 4)) = quaternionI := by
  simpa using quaternionIPowers_intCast 1

@[simp]
private theorem quaternionIPowers_two :
    quaternionIPowers (Multiplicative.ofAdd (2 : ZMod 4)) = quaternionI ^ 2 := by
  rw [← zpow_ofNat]
  exact quaternionIPowers_intCast 2

@[simp]
private theorem quaternionI_inv : quaternionI⁻¹ = -quaternionI := by
  apply inv_eq_of_mul_eq_one_right
  ext <;>
    norm_num [Quaternion.re_mul, Quaternion.imI_mul, Quaternion.imJ_mul,
      Quaternion.imK_mul]

private theorem quaternionIPowers_mul_quaternionJ (r : ZMod 4) :
    quaternionIPowers (Multiplicative.ofAdd r) * quaternionJ =
      quaternionJ * quaternionIPowers (Multiplicative.ofAdd (-r)) := by
  fin_cases r <;>
    ext <;>
    norm_num [quaternionIPowers_val, ZMod.val, pow_succ,
      Quaternion.re_mul, Quaternion.imI_mul, Quaternion.imJ_mul, Quaternion.imK_mul]

private theorem quaternionJ_sq :
    quaternionJ * quaternionJ =
      quaternionIPowers (Multiplicative.ofAdd (2 : ZMod 4)) := by
  ext <;>
    norm_num [quaternionIPowers_two, pow_succ,
      Quaternion.re_mul, Quaternion.imI_mul, Quaternion.imJ_mul, Quaternion.imK_mul]

/-- The structural map from mathlib's `QuaternionGroup 2` to the invertible
Hamiltonian quaternions. Its two normal forms are sent to `i^r` and `j i^r`. -/
noncomputable def quaternionGroupHom :
    QuaternionGroup 2 →* InvertibleQuaternions where
  toFun
    | QuaternionGroup.a r => quaternionIPowers (Multiplicative.ofAdd r)
    | QuaternionGroup.xa r => quaternionJ * quaternionIPowers (Multiplicative.ofAdd r)
  map_one' := by
    change quaternionIPowers (Multiplicative.ofAdd (0 : ZMod 4)) = 1
    exact map_one quaternionIPowers
  map_mul' := by
    rintro (r | r) (s | s)
    · exact map_mul quaternionIPowers _ _
    · simp only [QuaternionGroup.a_mul_xa]
      change quaternionJ * quaternionIPowers (Multiplicative.ofAdd (s - r)) =
        quaternionIPowers (Multiplicative.ofAdd r) *
          (quaternionJ * quaternionIPowers (Multiplicative.ofAdd s))
      rw [← mul_assoc, quaternionIPowers_mul_quaternionJ, mul_assoc,
        ← map_mul quaternionIPowers]
      apply congr_arg (quaternionJ * ·)
      apply congr_arg quaternionIPowers
      apply Multiplicative.toAdd.injective
      change s - r = -r + s
      abel
    · simp only [QuaternionGroup.xa_mul_a]
      change quaternionJ * quaternionIPowers (Multiplicative.ofAdd (r + s)) =
        (quaternionJ * quaternionIPowers (Multiplicative.ofAdd r)) *
          quaternionIPowers (Multiplicative.ofAdd s)
      rw [mul_assoc]
      apply congr_arg (quaternionJ * ·)
      rw [← map_mul quaternionIPowers]
      apply congr_arg quaternionIPowers
      apply Multiplicative.toAdd.injective
      rfl
    · simp only [QuaternionGroup.xa_mul_xa]
      change quaternionIPowers (Multiplicative.ofAdd ((2 : ZMod 4) + s - r)) =
        (quaternionJ * quaternionIPowers (Multiplicative.ofAdd r)) *
          (quaternionJ * quaternionIPowers (Multiplicative.ofAdd s))
      rw [mul_assoc quaternionJ, ← mul_assoc (quaternionIPowers (Multiplicative.ofAdd r)),
        quaternionIPowers_mul_quaternionJ,
        ← mul_assoc quaternionJ (quaternionJ *
          quaternionIPowers (Multiplicative.ofAdd (-r))),
        ← mul_assoc quaternionJ quaternionJ, quaternionJ_sq,
        ← map_mul quaternionIPowers, ← map_mul quaternionIPowers]
      apply congr_arg quaternionIPowers
      apply Multiplicative.toAdd.injective
      change 2 + s - r = 2 + (-r) + s
      abel

@[simp]
theorem quaternionGroupHom_a_two :
    quaternionGroupHom (QuaternionGroup.a 2) = -1 := by
  change quaternionIPowers (Multiplicative.ofAdd (2 : ZMod 4)) = -1
  rw [quaternionIPowers_two]
  ext <;>
    norm_num [pow_succ, Quaternion.re_mul,
      Quaternion.imI_mul, Quaternion.imJ_mul, Quaternion.imK_mul]

/-- The cyclic normal form has the expected value under the structural
quaternion-group homomorphism. -/
theorem quaternionGroupHom_a_val (r : ZMod 4) :
    quaternionGroupHom (QuaternionGroup.a r) = quaternionI ^ r.val :=
  quaternionIPowers_val r

/-- The twisted normal form has the expected value under the structural
quaternion-group homomorphism. -/
theorem quaternionGroupHom_xa_val (r : ZMod 4) :
    quaternionGroupHom (QuaternionGroup.xa r) =
      quaternionJ * quaternionI ^ r.val := by
  change quaternionJ * quaternionIPowers (Multiplicative.ofAdd r) = _
  rw [quaternionIPowers_val]

private theorem quaternionGroupHom_injective :
    Function.Injective quaternionGroupHom := by
  rintro (r | r) (s | s) h <;>
    fin_cases r <;>
    fin_cases s
  all_goals try rfl
  all_goals
    exfalso
    have h' := congrArg (fun q : InvertibleQuaternions =>
      (((q : ℍ[ℝ]).re, (q : ℍ[ℝ]).imI), ((q : ℍ[ℝ]).imJ, (q : ℍ[ℝ]).imK))) h
    norm_num [quaternionGroupHom, quaternionIPowers_val, ZMod.val,
      Quaternion.normSq_def', pow_succ, Quaternion.re_mul, Quaternion.imI_mul,
      Quaternion.imJ_mul, Quaternion.imK_mul] at h'

/-- The concrete quaternion subgroup of `ℍ[ℝ]ˣ`, obtained as the image of the
abstract quaternion group. -/
def quaternionSubgroup : Subgroup InvertibleQuaternions :=
  quaternionGroupHom.range

private theorem quaternionGroupHom_mem_closure (x : QuaternionGroup 2) :
    quaternionGroupHom x ∈ Subgroup.closure {quaternionI, quaternionJ} := by
  have hi : quaternionI ∈ Subgroup.closure {quaternionI, quaternionJ} :=
    Subgroup.subset_closure (by simp)
  cases x with
  | a r =>
      obtain ⟨m, rfl⟩ := ZMod.intCast_surjective r
      simpa [quaternionGroupHom, quaternionIPowers_intCast] using
        (Subgroup.closure {quaternionI, quaternionJ}).zpow_mem hi m
  | xa r =>
      obtain ⟨m, rfl⟩ := ZMod.intCast_surjective r
      have hj : quaternionJ ∈ Subgroup.closure {quaternionI, quaternionJ} :=
        Subgroup.subset_closure (by simp)
      simpa [quaternionGroupHom, quaternionIPowers_intCast] using
        (Subgroup.closure {quaternionI, quaternionJ}).mul_mem hj
          ((Subgroup.closure {quaternionI, quaternionJ}).zpow_mem hi m)

/-- The concrete quaternion subgroup is generated by the quaternion units
`i` and `j`. -/
theorem quaternionSubgroup_eq_closure :
    quaternionSubgroup = Subgroup.closure {quaternionI, quaternionJ} := by
  apply le_antisymm
  · rintro q ⟨x, rfl⟩
    exact quaternionGroupHom_mem_closure x
  · apply (Subgroup.closure_le quaternionSubgroup).2
    rintro q hq
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hq
    rcases hq with rfl | rfl
    · exact ⟨QuaternionGroup.a 1, by
        change quaternionIPowers (Multiplicative.ofAdd (1 : ZMod 4)) = quaternionI
        exact quaternionIPowers_one⟩
    · exact ⟨QuaternionGroup.xa 0, by simp [quaternionGroupHom]⟩

/-- The quaternion unit `i`, regarded as an element of the concrete quaternion subgroup. -/
@[expose]
def quaternionSubgroupI : quaternionSubgroup :=
  ⟨quaternionI, by
    rw [quaternionSubgroup_eq_closure]
    exact Subgroup.subset_closure (by simp)⟩

/-- The quaternion unit `j`, regarded as an element of the concrete quaternion subgroup. -/
@[expose]
def quaternionSubgroupJ : quaternionSubgroup :=
  ⟨quaternionJ, by
    rw [quaternionSubgroup_eq_closure]
    exact Subgroup.subset_closure (by simp)⟩

/-- The abstract quaternion group is explicitly equivalent to the concrete
quaternion subgroup generated by `i` and `j`. -/
noncomputable def quaternionGroupEquiv :
    QuaternionGroup 2 ≃* quaternionSubgroup :=
  MonoidHom.ofInjective quaternionGroupHom_injective

@[simp]
theorem quaternionGroupEquiv_apply (x : QuaternionGroup 2) :
    (quaternionGroupEquiv x : InvertibleQuaternions) =
      quaternionGroupHom x :=
  MonoidHom.ofInjective_apply quaternionGroupHom_injective

/-- An abstract cyclic normal form maps to the corresponding power of the
quaternion unit `i`. -/
theorem quaternionGroupEquiv_a_val (r : ZMod 4) :
    (quaternionGroupEquiv (QuaternionGroup.a r) : InvertibleQuaternions) =
      quaternionI ^ r.val := by
  rw [quaternionGroupEquiv_apply]
  exact quaternionGroupHom_a_val r

/-- A twisted abstract normal form maps to `j` times the corresponding power
of `i`. -/
theorem quaternionGroupEquiv_xa_val (r : ZMod 4) :
    (quaternionGroupEquiv (QuaternionGroup.xa r) : InvertibleQuaternions) =
      quaternionJ * quaternionI ^ r.val := by
  rw [quaternionGroupEquiv_apply]
  exact quaternionGroupHom_xa_val r

/-- The abstract representative of `1` maps to the identity quaternion. -/
@[simp]
theorem quaternionGroupEquiv_a_zero :
    (quaternionGroupEquiv (QuaternionGroup.a 0) : InvertibleQuaternions) = 1 := by
  rw [show (QuaternionGroup.a 0 : QuaternionGroup 2) = 1 by rfl, map_one]
  rfl

/-- The selected abstract generator maps to the quaternion unit `i`. -/
@[simp]
theorem quaternionGroupEquiv_a_one :
    (quaternionGroupEquiv (QuaternionGroup.a 1) : InvertibleQuaternions) =
      quaternionI := by
  rw [quaternionGroupEquiv_apply]
  exact quaternionIPowers_one

/-- The central abstract representative maps to the quaternion `-1`. -/
@[simp]
theorem quaternionGroupEquiv_a_two :
    (quaternionGroupEquiv (QuaternionGroup.a 2) : InvertibleQuaternions) = -1 := by
  rw [quaternionGroupEquiv_apply, quaternionGroupHom_a_two]

/-- The second selected abstract generator maps to the quaternion unit `j`. -/
@[simp]
theorem quaternionGroupEquiv_xa_zero :
    (quaternionGroupEquiv (QuaternionGroup.xa 0) : InvertibleQuaternions) =
      quaternionJ := by
  rw [quaternionGroupEquiv_apply]
  simp [quaternionGroupHom]

/-- The concrete quaternion subgroup inherits finiteness from its abstract
8-element model. -/
noncomputable instance : Fintype quaternionSubgroup :=
  Fintype.ofEquiv (QuaternionGroup 2) quaternionGroupEquiv

/-- The concrete quaternion subgroup has 8 elements. -/
@[simp]
theorem card_quaternionSubgroup :
    Fintype.card quaternionSubgroup = 8 := by
  rw [Fintype.card_congr quaternionGroupEquiv.symm.toEquiv, QuaternionGroup.card]

end

end BinaryTetrahedral
